### PR TITLE
Merging our Python 3 adaptations

### PR DESCRIPTION
**Pull request by lunkwill42**
This merges Python 3 adaptations from our fork onto kalombos' fork

There are only minor differences:

1. We suggest using relative imports in various locations
2. We suggest using explicit integer division operator `//` instead of casting to `int`
3. The `_valueToConstant` variable should also be constructed using `int2byte` as a replacement for `chr`

(we also reintroduce a comment that was lost from the original)

### CODE REVIEW

**Comment by lunkwill42** [comment]
I might add that our original changes made the inclusion of the `ipaddr` library Python 2-only, since `ipaddr` comes built-in to Python 3 under the name `ipaddress`. I've wiped these changes out from the merge, but they could of course be reintroduced.

**Comment by kalombos** [comment]
> We suggest using relative imports in various locations

Could you explain why does it need? Is it code style or something else?

> I might add that our original changes made the inclusion of the ipaddr library Python 2-only, since ipaddr comes built-in to Python 3 under the name ipaddress. I've wiped these changes out from the merge, but they could of course be reintroduced.

Sorry i didn't fully understand what are you talking about. For the moment `ipaddr` is included in the dependencies, see setup.py file. And `ipaddr` already supports python 3 in 2.2.0 version. But you can send the changes. I think it is a right decision to use built-in library instead of `ipaddr` and for python 2 you can use port of [ipaddress](https://github.com/phihag/ipaddress)

**Comment by lunkwill42** [comment]
>> We suggest using relative imports in various locations
>
> Could you explain why does it need? Is it code style or something
> else?

More or less. This signals that the imported modules are internal, and
you don't need to change the import lines if you one day choose to
change the name of the project.

> Sorry i didn't fully understand what are you talking about. For the
> moment `ipaddr` is included in the dependencies, see setup.py file.
> And `ipaddr` already supports python 3 in 2.2.0 version. But you can
> send the changes. I think it is a right decision to use built-in
> library instead of `ipaddr` and for python 2 you can use port of
> [ipaddress](https://github.com/phihag/ipaddress)

See commits 07acbc507473cc6446952fac964cd89641f811f6 and
b767af96743b1d8eb6ca1b37696b76f2aa39fa08 for the removed changes.

AFAICT, the Python 3 builtin `ipaddress` module was made from the
`ipaddr` module - but with a few changes, see PEP 3144
(https://www.python.org/dev/peps/pep-3144/).

I guess it's a style choice whether to use `ipaddress` and a Python2
backport of it, or use `ipaddr` on both versions - or as my PR
suggested.

As long as `ipaddr` module is available under Python 3, this is just
fine (and the changes from upstream will remain minimal). If we were to
drop Python 2 support at some point, it would be better to use
`ipaddress`, IMHO.

**Comment by kalombos** [comment]
> More or less. This signals that the imported modules are internal, and you don't need to change the import lines if you one day choose to change the name of the project.

thx for explanation.

> As long as `ipaddr` module is available under Python 3, this is just fine (and the changes from upstream will remain minimal). If we were to drop Python 2 support at some point, it would be better to use `ipaddress`, IMHO.

I think in the same way, i've seen your changes and i liked it. Please make a Pull Request with the changes.

**Pull request merged**
