### PR TITLE
Merge last three years of bugfixes from upstream

### PR DESCRIPTION
**Pull request by lunkwill42**
While upstream hasn't responded to any of our Python 3-related PRs, we could definitely benefit from merging fixes from upstream into our fork.

Needed to debug strange segfaults in the library, and wanted to make sure I had all upstream fixes first.

### CODE REVIEW

**Comment by kalombos** [comment]
Hi @lunkwill42 Unfortunately i have not used the library for a long time and don't maintain it. I can propose you to make a fork of the project and upload it to pypi with the changes and  better name than i did :)

**Comment by lunkwill42** [comment]
> Hi @lunkwill42 Unfortunately i have not used the library for a long time and don't maintain it. I can propose you to make a fork of the project and upload it to pypi with the changes and better name than i did :)

Sad to hear that, @kalombos. My repo is already a fork of the upstream repo, so the transition is easy.

I have no qualms about maintaining my own version on PyPI. My question is: Do you know of any other active users of pynetsnmp-2 on PyPI?

If not, I would kindly ask that you *transfer ownership of `pynetsnmp-2` on PyPI to me*. My username there is `mbrekkevold`. If I so wished to publish it under a new name, I could publish a final version of `pynetsnmp-2` that redirects to the new package.

**Comment by kalombos** [comment]
No I don't know any active users. I did the transfer on you on pypi

**Comment by lunkwill42** [comment]
Thanks for the coop on the fork, @kalombos, much appreciated! :-)

**Pull request closed without merging**
